# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g6TaEd5g8V63aSo4GApD_vsPX6LCzyA8
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import yfinance as yf
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import accuracy_score
# import requests # Import requests for web scraping
# 
# st.set_page_config(layout="wide")
# 
# st.title("📈 AI Market Dashboard")
# 
# # -----------------------------------
# # ✅ 지수 구성 종목 가져오기 (Wikipedia 스크래핑)
# # -----------------------------------
# @st.cache_data
# def get_sp500_constituents():
#     try:
#         headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
#         response = requests.get("https://en.wikipedia.org/wiki/List_of_S%26P_500_companies", headers=headers)
#         response.raise_for_status() # Raise HTTPError for bad responses (4xx or 5xx)
#         table = pd.read_html(response.text)[0]
#         return table["Symbol"].tolist()
#     except Exception as e:
#         st.error(f"S&P500 종목을 가져오는 데 실패했습니다: {e}. 기본 종목을 사용합니다.")
#         return ["AAPL", "MSFT", "NVDA", "AMZN", "GOOGL"]
# 
# @st.cache_data
# def get_nasdaq100_constituents():
#     try:
#         headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
#         response = requests.get("https://en.wikipedia.org/wiki/NASDAQ-100", headers=headers)
#         response.raise_for_status()
#         tables = pd.read_html(response.text)
#         for table in tables:
#             if "Ticker" in table.columns:
#                 return table["Ticker"].tolist()
#         st.error("NASDAQ100 테이블에서 'Ticker' 컬럼을 찾을 수 없습니다. 기본 종목을 사용합니다.")
#         return ["AAPL", "MSFT", "NVDA", "AMZN", "META", "TSLA"]
#     except Exception as e:
#         st.error(f"NASDAQ100 종목을 가져오는 데 실패했습니다: {e}. 기본 종목을 사용합니다.")
#         return ["AAPL", "MSFT", "NVDA", "AMZN", "META", "TSLA"]
# 
# @st.cache_data
# def get_dow_constituents():
#     try:
#         headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
#         response = requests.get("https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average", headers=headers)
#         response.raise_for_status()
#         tables = pd.read_html(response.text)
#         for table in tables:
#             if "Symbol" in table.columns:
#                 return table["Symbol"].tolist()
#         st.error("DOW30 테이블에서 'Symbol' 컬럼을 찾을 수 없습니다. 기본 종목을 사용합니다.")
#         return ["AAPL", "MSFT", "JPM", "V", "UNH", "HD", "PG"]
#     except Exception as e:
#         st.error(f"DOW30 종목을 가져오는 데 실패했습니다: {e}. 기본 종목을 사용합니다.")
#         return ["AAPL", "MSFT", "JPM", "V", "UNH", "HD", "PG"]
# 
# # ----------------------------------
# # 🔹 시장 선택 (사이드바)
# # ----------------------------------
# index_option = st.sidebar.selectbox(
#     "시장 선택",
#     ["S&P 500", "Nasdaq 100", "Dow Jones"]
# )
# 
# # 선택된 시장에 따른 전체 종목 리스트 가져오기
# if index_option == "S&P 500":
#     all_market_tickers = get_sp500_constituents()
# elif index_option == "Nasdaq 100":
#     all_market_tickers = get_nasdaq100_constituents()
# else: # Dow Jones
#     all_market_tickers = get_dow_constituents()
# 
# # ----------------------------------
# # 🔹 강세 종목 필터링 (MA20 > MA60)
# # ----------------------------------
# @st.cache_data
# def get_strong_tickers(market_tickers):
#     strong = []
#     # 성능을 위해 처음 50개 종목만 분석
#     for ticker in market_tickers[:50]:
#         try:
#             data = yf.download(ticker, period="6mo", progress=False)
#             if len(data) < 60: # MA 계산에 충분한 데이터 확인
#                 continue
#             data["MA20"] = data["Close"].rolling(20).mean()
#             data["MA60"] = data["Close"].rolling(60).mean()
#             if data["MA20"].iloc[-1] > data["MA60"].iloc[-1]:
#                 strong.append(ticker)
#         except:
#             continue
#     return strong
# 
# strong_tickers_list = get_strong_tickers(all_market_tickers)
# 
# # 강세 종목이 적을 경우 폴백
# if not strong_tickers_list or len(strong_tickers_list) < 5:
#     st.sidebar.info("강세 종목 필터링 결과가 적어, 다른 지수 내 종목들을 포함합니다.")
#     temp_list = list(strong_tickers_list)
#     added_count = 0
#     for t in all_market_tickers:
#         if t not in temp_list and added_count < 10: # 최대 10개 추가 종목
#             temp_list.append(t)
#             added_count += 1
#     if not temp_list: # 최종 폴백 (모든 시도 실패 시)
#         temp_list = ["AAPL", "MSFT", "GOOGL", "AMZN", "TSLA", "NVDA", "JPM"]
#     strong_tickers_list = temp_list
# 
# # ----------------------------------
# # 🔹 강세 종목 선택 (사이드바)
# # ----------------------------------
# selected_stock_ticker = st.sidebar.selectbox("강세 종목 선택", strong_tickers_list)
# 
# # ----------------------------------
# # 🔹 데이터 로드 (선택된 종목)
# # ----------------------------------
# data = yf.download(selected_stock_ticker, period="2y", interval="1d")
# data.dropna(inplace=True)
# 
# # ----------------------------------
# # 🔹 지표 생성 (선택된 종목)
# # ----------------------------------
# data["Return"] = data["Close"].pct_change()
# data["MA20"] = data["Close"].rolling(20).mean()
# data["MA60"] = data["Close"].rolling(60).mean()
# data["Volatility"] = data["Return"].rolling(20).std()
# 
# data.dropna(inplace=True)
# 
# # ----------------------------------
# # 🔹 머신러닝 분류 (다음날 상승 예측 - 선택된 종목)
# # ----------------------------------
# data["Target"] = np.where(data["Return"].shift(-1) > 0, 1, 0)
# 
# features = ["MA20", "MA60", "Volatility"]
# X = data[features]
# y = data["Target"]
# 
# X_train, X_test, y_train, y_test = train_test_split(
#     X, y, shuffle=False, test_size=0.2
# )
# 
# model = RandomForestClassifier()
# model.fit(X_train, y_train)
# 
# preds = model.predict(X_test)
# accuracy = accuracy_score(y_test, preds)
# 
# # 오늘 상승 확률
# latest_features = X.iloc[-1:].values
# up_prob = model.predict_proba(latest_features)[0][1]
# 
# # ----------------------------------
# # 🔹 전략 수익률 계산 (선택된 종목)
# # ----------------------------------
# data["Prediction"] = model.predict(X)
# data["Strategy_Return"] = data["Prediction"].shift(1) * data["Return"]
# 
# strategy_cum = (1 + data["Strategy_Return"]).cumprod()
# market_cum = (1 + data["Return"]).cumprod()
# 
# strategy_return = (strategy_cum.iloc[-1] - 1) * 100
# market_return = (market_cum.iloc[-1] - 1) * 100
# 
# current_price = float(data["Close"].iloc[-1]) # Ensure current_price is a scalar float
# 
# # ----------------------------------
# # 🔮 30일 몬테카를로 예측 (선택된 종목)
# # ----------------------------------
# future_days = 30
# returns = data["Return"].dropna()
# mu = returns.tail(60).mean()
# sigma = returns.tail(60).std()
# 
# last_price = current_price
# 
# simulations = 200
# price_paths = []
# 
# for _ in range(simulations):
#     prices = [last_price]
#     for _ in range(future_days):
#         shock = np.random.normal(mu, sigma)
#         prices.append(prices[-1] * (1 + shock))
#     price_paths.append(prices)
# 
# price_paths = np.array(price_paths)
# mean_path = price_paths.mean(axis=0)
# 
# # Ensure last_price is a scalar float to prevent pandas type alignment issues
# expected_returns = (mean_path - float(last_price)) / float(last_price)
# 
# ideal_day = np.argmax(expected_returns)
# ideal_price = mean_path[ideal_day]
# ideal_return = expected_returns[ideal_day] * 100
# 
# # ----------------------------------
# # 📊 지표 UI 표시 (선택된 종목)
# # ----------------------------------
# st.subheader(f"📊 {selected_stock_ticker} 핵심 지표")
# 
# col1, col2, col3 = st.columns(3)
# col4, col5, col6 = st.columns(3)
# 
# col1.metric("현재가", f"{current_price:.2f}")
# col2.metric("상승 확률", f"{up_prob*100:.2f}%")
# col3.metric("모델 정확도", f"{accuracy*100:.2f}%")
# 
# col4.metric("전략 수익률 (2년)", f"{strategy_return:.2f}%")
# col5.metric("시장 수익률 (2년)", f"{market_return:.2f}%")
# col6.metric("이상적 보유기간", f"{ideal_day}일")
# 
# st.markdown(
#     f"📌 보유기간 후 예상 주가: **{ideal_price:.2f}**  \n"
#     f"📈 기대 수익률: **{ideal_return:.2f}%**"
# )
# 
# # ----------------------------------
# # 📈 차트 (선택된 종목)
# # ----------------------------------
# st.subheader(f"📈 {selected_stock_ticker} 가격 & 예측")
# 
# fig = plt.figure(figsize=(12,6))
# plt.plot(data.index, data["Close"], label="Historical")
# 
# future_dates = pd.date_range(
#     data.index[-1], periods=future_days+1, freq="B"
# )
# 
# plt.plot(future_dates, mean_path, label="Predicted")
# 
# plt.scatter(future_dates[ideal_day], ideal_price, s=100)
# 
# plt.legend()
# st.pyplot(fig)

from pyngrok import ngrok
import subprocess
import os

# Kill any existing ngrok tunnels
os.system("kill -9 $(lsof -t -i:8501)")
ngrok.kill()

# Set up ngrok tunnel
public_url = ngrok.connect(8501)
print(f"Streamlit app available at: {public_url}")

# Run Streamlit in the background as a Python module
subprocess.Popen(["python", "-m", "streamlit", "run", "app.py", "--server.port", "8501", "--server.headless", "true"])

!pip install pyngrok

pip install streamlit yfinance pandas numpy ta requests scikit-learn xgboost

from pyngrok import ngrok

# Replace 'YOUR_NGROK_AUTH_TOKEN' with your actual ngrok authtoken
ngrok.set_auth_token("39bE0CpS2WHAaUX6PQ6rASAYJ0O_31kmVDWd725qaQTHa83Sz")